---
title: "index"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library('flexdashboard')
library('rgdal')
library("leaflet") 
library("leaflet.extras2")
library("sf")
library("tidyverse")
library("raster")
library("sp")
library("lubridate")

library(sf)
library(leafpop)
library(exactextractr)
```

```{r read.spatial, echo=FALSE}
pastos <- st_read(dsn = here::here("data/spatial/02_PASTOS_ADYACENTES/Pastos_adyacentes.shp"),
               quiet = TRUE)
ep <- st_read(dsn = here::here("data/spatial/01_EP_ANDALUCIA/EP_Andalucía.shp"),
               quiet = TRUE)

parcelas <- st_read(dsn = here::here("data/spatial/parcelas/GEO_PARCELAS.shp"),
               quiet = TRUE)
```




- Cobertura espacial:

  - Se han creado unas parcelas control virtuales (*n*=8) en el entorno de la Experiencia Piloto (*EP*). 
  - Se ha creado un *area of interest* (aoi) para extraer la información de satélite y posteriormente realizar los análisis.  
  

```{r schema-aoi, echo=FALSE}
# http://magjac.com/graphviz-visual-editor/
DiagrammeR::grViz("
digraph {
node [shape = box, fontname = Helvetica]
  EP; parcelas; AOI[label='Area of Interest']

node [shape = oval, color = green];

node [shape=parallelogram]
union[label='Spatial Union']; 
bb [label='Bounding box']; 
buffer[label = 'buffer 50 m'];

EP -> union;
parcelas -> union;
union -> bb -> buffer -> AOI
}
")
```

```{r read.spatial, echo=FALSE}
pastos <- st_read(dsn = here::here("data/spatial/02_PASTOS_ADYACENTES/Pastos_adyacentes.shp"),
               quiet = TRUE)
ep <- st_read(dsn = here::here("data/spatial/01_EP_ANDALUCIA/EP_Andalucía.shp"),
               quiet = TRUE)

parcelas <- st_read(dsn = here::here("data/spatial/parcelas/GEO_PARCELAS.shp"),
               quiet = TRUE)
```

```{r aoi, echo=FALSE}
aoi <- st_buffer(st_as_sfc(st_bbox(st_union(parcelas, ep))), dist = 50, endCapStyle = 'FLAT', joinStyle = 'MITRE', mitreLimit = 3)
```

**Study Area**

```{r plot.parcelas, out.width='100%', echo=FALSE, out.height='500px'}
mapviewOptions(default = TRUE)
# mapviewGetOption("basemaps")
mapviewOptions(basemaps = c(
  "Esri.WorldImagery", "CartoDB.Positron",
  "OpenStreetMap", "OpenTopoMap"
))

mapview(aoi, color = "yellow", col.regions = 'transparent', lwd = 1.5) +
mapview(ep,
        zcol = "ABREVIA", col.regions = c("#8dd3c7","#ff7f00","#bebada"), 
          layer.name = "EP",
  popup = popupTable(ep, zcol = c("ABREVIA", "Nombre_zon", "SUPERFICIE"))
) +
  mapview(parcelas,
    layer.name = "Parcelas", zcol="TIPO", col.regions = c("blue","red"),
    popup = popupTable(parcelas,
      zcol = c("NOMBRE", "TRATAMIENT", "TIPO")
    ), 
    label = parcelas$NOMBRE
  ) 
```

